import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4">
          <Link href="/" className="text-white text-lg font-semibold">
            Giriş Ekranı
          </Link>
          <span className="mx-4 text-gray-400">|</span>
          <Link
            href="/liste-sayfasi"
            className="text-white text-lg font-semibold"
          >
            Personeller
          </Link>
          <span className="mx-4 text-gray-400">|</span>
          <Link
            href="/ekleme-sayfasi"
            className="text-white text-lg font-semibold"
          >
            Personel Ekle
          </Link>
          <span className="mx-4 text-gray-400">|</span>
        </nav>
        {children}
      </body>
    </html>
  );
}
