export const liste= [
  { isim: 'Bora',
    soyisim: 'Hamurcu' ,
    yas:'22',
    emekli: false,
    cv:'itü mezunu, yazılım mühendisi',
  },
  { isim: 'Mustafa',
    soyisim: 'xd' ,
    yas: '25',
    emekli: false,
    cv: 'Boğaziçi Üniversitesi mezunu, veri analisti',
  },
 { isim: 'Mehmet',
    soyisim: 'Yılmaz' ,
    yas: '30',
    emekli: true,
    cv: 'ODTÜ mezunu, proje yöneticisi',
  },
  { isim: 'Ayşe',
    soyisim: 'Demir' ,
    yas: '28',
    emekli: false,
    cv: 'İstanbul Üniversitesi mezunu, pazarlama uzmanı',
  },
  { isim: 'Fatma',
    soyisim: 'Kaya' ,
    yas: '35',
    emekli: true,
    cv: 'Hacettepe Üniversitesi mezunu, insan kaynakları uzmanı',
  }];